OpenZeppelin/polkadot-runtime-templates

runtime/Cargo.toml

without these changes runtime does not compile because pallet-proxy is leaking `std`
Closes #38
Highlights #28 by showing that the current CI does NOT check if the runtime builds and this has led to a bug

Fix runtime build by including all proxy features

---

runtime/build.rs

Fixes #79 
Reverts the code to substrate original for `build.rs`. It was changed in #68 due to compilation errors, but I suspect these changes are not related to compilation errors.

revert code to substrate original

---

.github/workflows/cargo-tests.yml

Fixes #47 
I've tried on my Windows machine, and found out that the error on Windows is not specific to our CI setup, but general to all windows machines. 
The details are provided in the issue if you want to take a deeper look.
In short, `polkadot-sdk` does not support Windows, and we should remove `windows` tests from our CI until Windows is supported by the upstream.

remove windows from ci tests

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/runtimes/generic.adoc
docs/templates/runtime.adoc
runtime/src/lib.rs

Fixes #61 
There are some modifications that I've made. I'm going to explain them below. If you disagree with them, feel free to comment, or we can discuss them on a meeting.
For the `runtime template` doc:
- I removed config description for each pallet
- it would make the runtime doc too long 
- the configs for important pallets are already explained in their respective docs
- I know that the reason to include config in runtime docs is to explain what is special about its config. However, explaining the config for each pallet is an overkill imo. 
- so, I put another section for *important config changes specific to this runtime`
- for generic runtime documentation, comparing it with other templates does not serve any purpose imo
- moved `pallet proxy` from `system` to `governance`, to …

Generic documentation

---

.github/workflows/cargo-tests.yml

Fixes #119 
Explanation is present in the issue, but TL;DR:
`clippy` is a superset of `check` command, and now both of them are using `--release` flag, which makes `check` command redundant.

remove redundant action

---

Cargo.lock
Cargo.toml
node/Cargo.toml
runtime/Cargo.toml

This PR bumps the version for `runtime` and `node` to `0.1.2`, to be consistent with the changelog we have.
From now on, we should remember to bump the version in the code whenever we make some changes to changelog.
Also, somehow, github decided to merge the previous PR before tests have successfully passed (happens sometimes 🤷). And there was a cargo.toml formatting error. This PR also fixes that.

Fix cargo toml formatting and bump versions

---

.gitignore
scripts/zombienet.sh
zombienet-config/README.md
zombienet-config/devnet.toml
zombienet.sh

This PR adds zombienet utilities to the template.
By running
```bash
$ ./zombienet.sh build && ./zombienet.sh devnet
```
it will spawn a local relay chain and parachain. Pretty useful for testing features within the project.
Please note whenever the template is prepared for async backing zombienet configuration will have to be updated. For more info see [here](https://github.com/OpenZeppelin/polkadot-runtime-template/commit/f34feff9293cf42fb4163f68382474bb6d0bc42c).

add zombienet configuration

---

runtime/src/lib.rs

Fixes #143 
I've confused myself with `v0.1` and `main` branch, and also introduced fixes to `main` with the other PR #151.
This one keeps the scope only for `v0.1`, will be easier to inspect for audit purposes. 
After we merge `v0.1` into `main`, I'll update the other PR #151 and then we can merge it, for now, I'll keep that one open.
This PR:
- adds explanation to SS58 prefix (42)
- merges some of the unnecessarily separated `parameter_types!` blocks
- and fixes some typos

better explanation for constants

---

docs/antora.yml

During the release preparation we forgot to update the docs version.
We do not need it under the release tag, it is needed only for the correct representation on docs website.

Updated docs version

---

docs/modules/ROOT/pages/index.adoc
docs/modules/ROOT/pages/runtimes/generic.adoc

Fixes #177 
- Remove security warning from docs after the audit and since release v1.0.0 is ready
- Fix list formatting issue

Remove security warning from docs and fix style in list

---

docs/modules/ROOT/pages/index.adoc
docs/modules/ROOT/pages/runtimes/generic.adoc

Same as #178 but for the branch where the docs are currently published

remove security warning from docs and fix list

---

docs/modules/ROOT/pages/index.adoc

` --disable-default-nodes` does not exist. Perhaps, the intent was to use `--disable-default-bootnode`.

Update index.adoc - fix chainspec generation command

---

evm-template/Cargo.lock
evm-template/Cargo.toml
evm-template/node/src/command.rs
evm-template/node/src/service.rs
evm-template/runtime/src/lib.rs
evm-template/runtime/src/xcm_config.rs
generic-template/node/src/service.rs

Frontier did not have `polkadot-v1.10.0` branch 🤦🏻‍♂️🤦🏻‍♂️🤦🏻‍♂️
So I did create it in our fork, and then updated these dependencies. 
Thanks to @KitHat for solving the problems related to node part.
Fixes #207

Upgrade evm dependencies

---

evm-template/node/src/eth.rs
evm-template/node/src/service.rs

There is a bug that Santiago mentioned and I also observed an issue during the generation of wasm or node launch:
```
Error: Service(Client(VersionInvalid("Other error happened while constructing the runtime: runtime requires function imports which are not present on the host: 'env:ext_storage_proof_size_storage_proof_size_version_1'")))
2024-06-11 09:25:43 [Parachain] Cannot create a runtime error=Other("runtime requires function imports which are not present on the host: 'env:ext_storage_proof_size_storage_proof_size_version_1'")
```

fixed "missing host function" bug

---

evm-template/runtime/src/apis.rs
evm-template/runtime/src/configs/mod.rs
evm-template/runtime/src/constants.rs
evm-template/runtime/src/types.rs
generic-template/runtime/src/types.rs

This PR ports the trivial audit fixes for generic template to evm template. Partially addresses #237 
Below is the recap of the audit findings and the related issues & PRs:
---
Except 3.2.1 (`FeeManager`), all the remaining ones are related to Weights/Benchmarking, and I think they will be solved once #235  is completed. Please correct me if I'm wrong @KitHat.

Port the trivial audit fixes to evm

---

.github/workflows/evm.yml
.github/workflows/generic.yml

Fixes #259
Our workflows take about 50min each on every PR(on main it is longer given we also run it on mac OS). This can be improved using [sccache](https://github.com/mozilla/sccache/) which avoids compilation when possible. It is common in polkadot projects to have this given long build times.
**With this, subsequent runs take around 35min.** 
- Add sccache step
- Use [nextest](https://github.com/nextest-rs/nextest) for tests, which is up to 3x faster than cargo test, and also shows the results in a much nicer format. It also shows you if you have some slow tests. Currently this is not a big advantage, since our tests are quick, but even the formatting is worth it I think.

Add sccache and use nextest in our workflow

---

.github/pull_request_template.md
.github/workflows/evm.yml
.github/workflows/generic.yml
evm-template/Cargo.lock
generic-template/Cargo.lock

Fixes #242
Modified script that runs benchmarks to also build the binary for them.
Added the benchmark run to the CI.
Added a checkbox to verify the pallet inclusion to the benchmarking run.

Add benchmark tests to CI

---

docs/modules/ROOT/pages/guides/testing_with_zombienet.adoc

Removes some duplicated commands that was initially there for the demo. 
Also fixing some typos.

fix typos in testing with zombienet guide

---

README.md
docs/modules/ROOT/pages/index.adoc

- Remove security warning for EVM template now that we have published the audit and released.
- Add some details about the benefits of the EVM template.
- Fix some links
- Fix a link that was broken in the home page for the Generic Template

Remove security warning for EVM template and fix broken link in docs

---

.github/dependabot.yml

Fixes #278 
This allows dependabot to open PRs for both vulnerable dependencies and just regular dependency updates. For polkadot sdk we ingore it and continue with manual updates(idea borrowed from [Frontier](https://github.com/polkadot-evm/frontier/blob/master/.github/dependabot.yml)) since we want to retain control for when and how to update these.

Allow dependabod to automatically open PRs

---

evm-template/zombienet-config/devnet.toml
generic-template/zombienet-config/devnet.toml

This PR adds `force_decorator = "generic-evm"` in the `devnet.toml` of the EVM parachain as suggested in https://github.com/paritytech/zombienet/issues/1826. Closes https://github.com/OpenZeppelin/polkadot-runtime-templates/issues/289
This PR also renames the parachain binaries in the Zombienet files of the `generic-template` and `evm-template` to enhance the UX. With this change users don't have to to manually rename the binaries.

fix: rename templates binaries in the zombienet files

---

.gitignore
evm-template/scripts/zombienet.sh
generic-template/scripts/zombienet.sh

Fixes #291 and finalizes #289 
Follow up on #290

fix zombienet scripts for accountid20 compatibility

---

.github/workflows/evm.yml
.github/workflows/generic.yml

Fixes #296 
Disabling code coverage for now as agreed upon

disable code coverage for now

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/core_implementation.yml
.github/ISSUE_TEMPLATE/feature_request.yml

When a new issue is added we don't have a clear process/way to determine if it is valid, what works is needed, etc. By adding this label at least we can filter out and see what issues are new and someone from our team can assign the proper labels and decide if it is valid.

Add needs triage issue label for new issues

---

.github/workflows/generic-weekly-fuzzer.yml
evm-template/template-fuzzer/src/main.rs

Fix workflow versions

---

evm-template/runtime/src/apis.rs
evm-template/runtime/src/configs/xcm_config.rs
generic-template/runtime/src/apis.rs
generic-template/runtime/src/configs/mod.rs
generic-template/runtime/src/configs/xcm_config.rs
generic-template/runtime/src/types.rs

Updated configuration and benchmarking for XCM pallet.
In relation to original issue:
Fixed benchmarks:
- `execute`
- `transfer_assets`
- `reserve_transfer_assets`
Benchmarks that were left unchanged:
- `execute_blob` -- it was removed in `stable-2407`.
- `teleport_assets` -- we are not going to allow to teleport assets over the XCM, so we will not spend time on fixing this benchmarks. If you are willing to do it, feel free to contribute.
Fixes #305

#305 Fixing unexpectedly high weights for XCM pallet

---

docs/modules/ROOT/pages/guides/async_backing.adoc
docs/modules/ROOT/pages/guides/quick_start.adoc
docs/modules/ROOT/pages/guides/testing_with_zombienet.adoc
docs/modules/ROOT/pages/index.adoc
docs/modules/ROOT/pages/runtimes/evm.adoc
evm-template/Cargo.lock
evm-template/Cargo.toml
evm-template/node/Cargo.toml
evm-template/node/src/chain_spec.rs
evm-template/node/src/cli.rs
evm-template/node/src/command.rs
evm-template/polkadot-launch/config.json
evm-template/runtime/src/lib.rs
evm-template/scripts/zombienet.sh
evm-template/zombienet-config/devnet.toml
generic-template/Cargo.lock
generic-template/Cargo.toml
generic-template/node/Cargo.toml
generic-template/node/src/chain_spec.rs
generic-template/node/src/cli.rs
generic-template/node/src/command.rs
generic-template/runtime/src/lib.rs
generic-template/scripts/zombienet.sh
generic-template/zombienet-config/devnet.toml

Fixes #318 
- Migrate all references from rococo to paseo(both in docs and chainspec, code, etc).
- Slightly improve docs and fix some broken links

Change all references from rococo to paseo

---

docs/modules/ROOT/pages/guides/quick_start.adoc
docs/modules/ROOT/pages/guides/testing_with_zombienet.adoc
evm-template/node/src/chain_spec.rs
evm-template/node/src/cli.rs
evm-template/polkadot-launch/config.json
evm-template/scripts/zombienet.sh
evm-template/zombienet-config/devnet.toml
generic-template/node/src/chain_spec.rs
generic-template/node/src/cli.rs
generic-template/scripts/zombienet.sh
generic-template/zombienet-config/devnet.toml

Fixes #352 
Currently polkadot-sdk does not support `paseo-local` option for the CLI arguments. 
We will use `rococo-local` till `paseo-local` option is implemented.

roll back to rococo local for now

---

.gitignore
generic-template/runtime/src/configs/asset_config.rs
generic-template/runtime/src/configs/governance/origins.rs
generic-template/runtime/src/configs/governance/tracks.rs
generic-template/runtime/src/lib.rs
generic-template/runtime/src/types.rs

Add unit tests

---

.github/workflows/evm-weekly-fuzzer.yml
.gitignore
evm-template/Cargo.lock
evm-template/template-fuzzer/Cargo.toml
evm-template/template-fuzzer/src/main.rs
generic-template/Cargo.lock
generic-template/template-fuzzer/Cargo.toml
generic-template/template-fuzzer/src/main.rs

Improve Fuzzing runs

---

.github/workflows/evm-weekly-fuzzer.yml
.github/workflows/generic-weekly-fuzzer.yml

Missing protobuf compiler failed the fuzzing run coverage generation.
There was a successful run with these changes: https://github.com/OpenZeppelin/polkadot-runtime-templates/actions/runs/13071431290

Fix missing protoc in fuzzing run
