- .github/workflows/cargo-tests.yml
- docs/templates/pallet.adoc
- Fixes #54 
- adds `branch/release` field to pallet template documentation
- fixes some typos
> Docs ozgun

- docs/antora.yml
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/pallets/proxy.adoc
- docs/templates/pallet.adoc
That's a PR with docs moved to public repository.
> Proxy Documentation

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/message-queue.adoc
- docs/modules/ROOT/pages/pallets/message-queue.adoc
- docs/modules/ROOT/pages/pallets/proxy.adoc
Related to #15 (after xcmp queue docs, the issue will be completely closed)
> Message queue docs

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/pallets/aura_ext.adoc
- docs/modules/ROOT/pages/pallets/message-queue.adoc
- docs/modules/ROOT/pages/pallets/proxy.adoc
- docs/templates/pallet.adoc
- moved `aura-ext` documentation
- added more details to `proxy` docs
- updated template and fixed a glitch
> `aura-ext` documentation moved

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
During my first week, I configured the issue templates to assign the new ones to me. After you guys joined, I forgot to change it back. 
Also, fixed a typo.
> fix issue templates

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/pallets/aura_ext.adoc
- docs/modules/ROOT/pages/pallets/collator-selection.adoc
- docs/modules/ROOT/pages/pallets/parachain-system.adoc
Final part of my docs moved to public repo
> Consensus Docs

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/misc/multisig-accounts.adoc
- docs/modules/ROOT/pages/pallets/multisig.adoc
> multisig docs

- docs/modules/ROOT/pages/pallets/multisig.adoc
shortening the explanation for niche details, and fixing an error :)
> improve multisig documentation for niche details

- docs/modules/ROOT/pages/index.adoc
Fixes #60
An index page for our documentation was added.
> Index page

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/pallets/xcmp-queue.adoc
> Xcmp queue docs

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/pallets/balances.adoc
- docs/modules/ROOT/pages/pallets/proxy.adoc
- docs/modules/ROOT/pages/pallets/transaction_payment.adoc
> Balances doc

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/glossary.adoc
- docs/modules/ROOT/pages/pallets/balances.adoc
- docs/modules/ROOT/pages/pallets/collator-selection.adoc
- docs/modules/ROOT/pages/pallets/multisig.adoc
- docs/modules/ROOT/pages/pallets/pallet_xcm.adoc
- docs/modules/ROOT/pages/pallets/parachain-system.adoc
- docs/modules/ROOT/pages/pallets/proxy.adoc
- docs/modules/ROOT/pages/pallets/transaction_payment.adoc
- docs/modules/ROOT/pages/pallets/xcmp-queue.adoc
- docs/modules/ROOT/pages/runtime/xcm_executor.adoc
- docs/templates/pallet.adoc
Fixes #52
Introduces a glossary and links to it from different pages.
Notice for all reviewers: please, go through the documents that you have created and check if the links are in place.
> Glossary introduction

- docs/modules/ROOT/nav.adoc
> making misc section visible on side bar

- runtime/src/lib.rs
Fixes #100 
Multisig pallet's index is altered, this is a breaking change (announcing it for the sake of best practices. Introducing a breaking change should be ok at this stage for our project).
> group pallets in a consistent way for documentation

- docs/modules/ROOT/pages/index.adoc
This is an update for tutorial that reflects actions that were done to set up a parathread against Rococo.
Closes #84
> #84 Update the tutorial for parathread deployment.

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/glossary.adoc
- docs/modules/ROOT/pages/pallets/assets.adoc
> Add documentation for `pallet_assets`

- runtime/src/lib.rs
Added a filter that stops anonymous proxy calls.
Fixes #12
> Filter out anonymous proxy calls

- .github/workflows/cargo-tests.yml
Fixes #117 
Details are on the issue
> improve ci for space

- Cargo.lock
- Cargo.toml
- template-fuzzer/Cargo.toml
- template-fuzzer/Dockerfile
- template-fuzzer/README.md
- template-fuzzer/run-fuzzer.sh
- template-fuzzer/src/main.rs
> Fuzzer Integration

- .github/workflows/cargo-tests.yml
- Cargo.lock
- Cargo.toml
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/guides/async_backing.adoc
- node/Cargo.toml
- node/src/service.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
- runtime/tests/constants_test.rs
Fixes #97
* Added async backing into the runtime -- updated hooks and configs
* Added async backing into the node and put it under the feature.
> #97 added async backing to runtime and node

- scripts/zombienet.sh
- zombienet-config/README.md
- zombienet-config/devnet.toml
Fixes #157 
Added zombie net config from main to release
> Add Zombienet Config to Release

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/pallets/assets.adoc
- docs/modules/ROOT/pages/pallets/aura_ext.adoc
- docs/modules/ROOT/pages/pallets/balances.adoc
- docs/modules/ROOT/pages/pallets/collator-selection.adoc
- docs/modules/ROOT/pages/pallets/message-queue.adoc
- docs/modules/ROOT/pages/pallets/multisig.adoc
- docs/modules/ROOT/pages/pallets/parachain-system.adoc
- docs/modules/ROOT/pages/pallets/proxy.adoc
- docs/modules/ROOT/pages/pallets/transaction_payment.adoc
- docs/modules/ROOT/pages/pallets/xcm.adoc
- docs/modules/ROOT/pages/pallets/xcmp-queue.adoc
Updated documentation to v.1.7.0
> Cleanup docs for the release

- docs/antora.yml
- docs/modules/ROOT/pages/pallets/assets.adoc
- docs/modules/ROOT/pages/pallets/aura_ext.adoc
- docs/modules/ROOT/pages/pallets/balances.adoc
- docs/modules/ROOT/pages/pallets/collator-selection.adoc
- docs/modules/ROOT/pages/pallets/message-queue.adoc
- docs/modules/ROOT/pages/pallets/multisig.adoc
- docs/modules/ROOT/pages/pallets/parachain-system.adoc
- docs/modules/ROOT/pages/pallets/proxy.adoc
- docs/modules/ROOT/pages/pallets/transaction_payment.adoc
- docs/modules/ROOT/pages/pallets/xcm.adoc
- docs/modules/ROOT/pages/pallets/xcmp-queue.adoc
- docs/modules/ROOT/pages/runtime/xcm_executor.adoc
- docs/templates/pallet.adoc
> updated docs to v1.10

- Cargo.lock
- Cargo.toml
- node/src/command.rs
- node/src/service.rs
- runtime/src/lib.rs
- runtime/src/xcm_config.rs
Fixes #161 
To make the update, followed: 
- release notes 
- PRs
- parachain template provided by Parity
Will tackle documentation updates in another PR
> updated dependencies to v1.10.0

- runtime/src/lib.rs
- runtime/src/xcm_config.rs
Fix the fee manager set to `()`
> Fix the FeeManager setting

- CHANGELOG.md
- Cargo.lock
- node/Cargo.toml
- runtime/Cargo.toml
Before release, let's bump version and update changelog
> changelog and version bump

- runtime/src/lib.rs
As suggested in 4.3 (#143), there are a couple of improvements that we can make to further improve clarity on constants.
This PR:
- renames `MaxScheduledPerBlock` to `MaxScheduledRuntimeCallsPerBlock`
- merges some of the unnecessarily separated `parameter_types!` blocks
> clearer constant namings and explanations

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/core_implementation.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/workflows/generic.yml
- .gitignore
Fixes the workflow for the generic runtime template and renames the workflow name respectively for the generic runtime template.
> workflow fix

- .gitignore
- evm-template/Cargo.lock
- evm-template/Cargo.toml
- evm-template/runtime/Cargo.toml
- evm-template/runtime/src/lib.rs
- evm-template/template-fuzzer/src/main.rs
This is a moved PR from https://github.com/OpenZeppelin/polkadot-evm-runtime-template/pull/20
Fixes #184 and #185 
Tasklist:
> Integrated EVM and Ethereum pallets

- README.md
- docs/modules/ROOT/pages/index.adoc
Please review the changed content. If you think wordings can be improved or you want to add/change anything, we can do so in this PR.
> readme and docs update for monorepo

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/guides/contract_migration.adoc
- evm-template/Cargo.lock
- evm-template/node/Cargo.toml
- evm-template/node/src/chain_spec.rs
Also added some predefined keys to the chainspec that are mention in a new guide.
Fixes #188
> #188 Added a guide for contract migration

- evm-template/node/src/chain_spec.rs
- generic-template/node/src/chain_spec.rs
Fixes #203 
For the details and explanations, please see the related issue.
> add property to node for each template

- evm-template/Cargo.lock
- evm-template/Cargo.toml
- evm-template/runtime/Cargo.toml
- evm-template/runtime/src/types.rs
- generic-template/Cargo.lock
- generic-template/Cargo.toml
- generic-template/runtime/Cargo.toml
- generic-template/runtime/src/types.rs
> Add pov reclaim

- docs/modules/ROOT/pages/index.adoc
> Add the option to sync faster with Rococo to the docs

- docs/modules/ROOT/pages/index.adoc
> Port docs to sync faster with Rococo to our audit branch

- evm-template/node/Cargo.toml
- evm-template/node/src/contracts/abi.rs
- evm-template/node/src/contracts/forge.rs
- evm-template/node/src/contracts/hardhat.rs
- evm-template/node/src/contracts/mod.rs
- evm-template/runtime/src/configs/governance/mod.rs
- evm-template/runtime/src/configs/xcm_config.rs
- evm-template/runtime/tests/constants_test.rs
- evm-template/rust-toolchain.toml
- evm-template/template-fuzzer/src/main.rs
- generic-template/runtime/src/configs/governance/mod.rs
- generic-template/runtime/src/configs/xcm_config.rs
- generic-template/runtime/tests/constants_test.rs
- generic-template/rust-toolchain.toml
- generic-template/template-fuzzer/src/main.rs
Duplicate of #248 for `v2` branch
Fixes #247
> Max remote lock consumers

- evm-template/runtime/src/configs/asset_config.rs
- evm-template/runtime/src/configs/governance/mod.rs
- evm-template/runtime/src/configs/mod.rs
- evm-template/runtime/src/configs/xcm_config.rs
- evm-template/runtime/src/constants.rs
- generic-template/runtime/src/configs/governance/mod.rs
- generic-template/runtime/src/configs/mod.rs
- generic-template/runtime/src/configs/xcm_config.rs
Updated the docs for the security review.
> Docs Update

- evm-template/runtime/src/configs/xcm_config.rs
- evm-template/runtime/tests/constants_test.rs
- generic-template/runtime/src/configs/xcm_config.rs
- generic-template/runtime/tests/constants_test.rs
Update XCM constants to align with Kusama implementation
> Fix XCM constants

- docs/modules/ROOT/pages/guides/testing_with_zombienet.adoc
> improving zombienet guide

- generic-template/template-fuzzer/src/main.rs
After my last PR CI run on main have failed. This PR fixes it.
For some reason Github haven't triggered a Generic template run
> Fix broken CI run on main

- .github/workflows/typos.yml
- docs/modules/ROOT/pages/guides/predeployed_contracts.adoc
- docs/modules/ROOT/pages/pallets/multisig.adoc
- docs/modules/ROOT/pages/pallets/parachain-system.adoc
- docs/modules/ROOT/pages/pallets/transaction_payment.adoc
- evm-template/node/src/cli.rs
- evm-template/node/src/eth.rs
- evm-template/runtime/src/constants.rs
- evm-template/template-fuzzer/src/main.rs
- generic-template/node/src/cli.rs
- generic-template/template-fuzzer/src/main.rs
Fixes #65 
Wouldn't it be great if we didn't need to worry about dumb typos slipping into the codebase? 😅 
This PR:
- Fixes existing typos
- Adds a [GH Action](https://github.com/crate-ci/typos) that will check on every PR if we have typos
You can also install this locally and check/fix before pushing to the repo.
> Fix typos and add GH action that checks them

- .github/workflows/generic-weekly-fuzzer.yml
Fixes #302 
This is a small fix required on all new machines to run fuzz testing.
> #302 Fix Weekly Fuzzing Run

- .gitignore
- evm-template/scripts/zombienet.sh
- evm-template/zombienet-config/devnet.toml
- generic-template/scripts/zombienet.sh
- generic-template/zombienet-config/devnet.toml
Porting zombienet fixes to `v2` branch for the new release
> zombienet fixes

- .github/workflows/generic-weekly-fuzzer.yml
This goes out of the issue because it requires several consecutive PRs to test the builds
> Fix AFL build for fuzzing run

- evm-template/Cargo.lock
- evm-template/Cargo.toml
- evm-template/runtime/Cargo.toml
- evm-template/runtime/src/configs/xcm_config.rs
Fixes: #308 and #309 
There will be follow up PRs on snowbridge integration
> use asset hub as reserve

- .github/workflows/generic-weekly-fuzzer.yml
* Added an AFL flag to be able to run the fuzzer on GitHub runner
* zipped the outputs to save them as an artifact
> Fix Weekly Fuzzer Run

- .github/workflows/coverage.yml
- .github/workflows/evm.yml
- .github/workflows/generic.yml
Fixes #260  
Example of report:
https://app.codecov.io/github/OpenZeppelin/polkadot-runtime-templates/commit/eb0c045b434edc1a71c958a33a63ce3671b53982/tree
> Enable Coverage Uploading

- .github/workflows/coverage.yml
- evm-template/runtime/src/configs/mod.rs
- evm-template/runtime/src/configs/xcm_config.rs
- evm-template/runtime/src/types.rs
- evm-template/runtime/tests/constants_test.rs
- evm-template/runtime/tests/storage.rs
- generic-template/runtime/src/configs/mod.rs
- generic-template/runtime/src/types.rs
- generic-template/runtime/tests/constants_test.rs
- generic-template/runtime/tests/storage.rs
> Fix tanssi on main

- .github/workflows/coverage.yml
- .github/workflows/evm.yml
- .github/workflows/generic.yml
> Remove macOS runner
